  
version: "2.1"
services:

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: api
    healthcheck:
      test: pg_isready -U postgres
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - postgres
    ports:
      - "5432:5432"

networks:
  postgres:
    driver: bridge