version: "2.1"
services:
  frontend:
    build:
      context: frontend
    ports:
      - "3000:3000"

  backend:
    build:
      context: backend
    networks:
      - postgres
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "5000:5000"

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: backend
    healthcheck:
      test: pg_isready -U postgres
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - postgres
    ports:
      - "5432:5432"

networks:
  postgres:
    driver: bridge
