namespace backend.Features.Messages.Services;

public class MessageService : IMessageService
{

    private readonly static string[] MessageContents = new[]
    {
        "Some cool message",
        "Another cool message",
        "Some other message not as cool"
    };
    
    private string _GenerateUUID()
    {
        return Guid.NewGuid().ToString();;
    }
    
    public IEnumerable<Message> List()
    {
        return MessageContents.Select(content => new Message()
        {
            Uuid = _GenerateUUID(),
            Content = content
        });
    }

    public Message Create()
    {
        return new Message()
        {
            Uuid = _GenerateUUID(),
            Content = "A message generated by the backend at " + DateTime.Now
        };
    }
}